### ISSUE TITLE
а шо как?

### ISSUE THREAD

**Issue by AndrewNagikh** [kotisoff/discord-player-yandexmusic#1]
Привет, нашел твой экстрактор для яндекс музыки, но собственно в толк не возьму как он плеер ищет именно по яндекс музыки, дефолтные searchEngine я как понял добавлять нет смысла
Собственно вопрос, в твоем боте работают яндекс ссылки?
Если - да
<img width="942" alt="Снимок экрана 2024-07-07 в 05 33 18" src="https://github.com/kotisoff/discord-player-yandexmusic/assets/107129839/841cc4eb-f480-46fa-a00b-05f875498b7b">
? буду рад если объяснишь как оно работает

**Comment by kotisoff** [comment]
Привет! Надеюсь я не слишком поздно.
Я делал по экстрактору другого чела, но вроде как не сильно далеко от его варианта ушёл.
Не особо смотрел сурсы discord-player, но думаю, если не указывать в player.search конкретный экстрактор, он в цикле из зарегистрированных экстракторов вызывает для каждого метод validate и первый вернувший true будет целевым для поиска.
Мой способ более костыльный, тк я совсем недавно познакомился с discord-player, но вот [моя версия команды](https://github.com/kotisoff/kitbot/blob/typescript/commands/voice/music/play.ts).
Тут мой бот жуёт только ссылки из яндекс музыки, а ищет из ютуба.

**Comment by AndrewNagikh** [comment]
> Привет! Надеюсь я не слишком поздно.
> Я делал по экстрактору другого чела, но вроде как не сильно далеко от его варианта ушёл.
> Не особо смотрел сурсы discord-player, но думаю, если не указывать в player.search конкретный экстрактор, он в цикле из зарегистрированных экстракторов вызывает для каждого метод validate и первый вернувший true будет целевым для поиска.
> Мой способ более костыльный, тк я совсем недавно познакомился с discord-player, но вот [моя версия команды](https://github.com/kotisoff/kitbot/blob/typescript/commands/voice/music/play.ts).
> Тут мой бот жуёт только ссылки из яндекс музыки, а ищет из ютуба.

Понял, посмотрю, спасибо)
В принципе я к похожему пришел, взял из браузера запрос Radio со всеми куками, вызываю его в ноде, а название трека и исполнителя уже передаю в ютубовый поисковик
