### ISSUE TITLE
Неправильное форматирование URL плейлистов

### ISSUE THREAD

**Issue by rpastuhov** [kotisoff/discord-player-yandexmusic#2]
Я столкнулся с проблемой форматирования URL для плейлистов. Текущая регулярная строка не учитывает некоторые символы, которые могут появляться в ID Яндекса, такие как `.`, `-`, `=`, и `_`, возможно есть ещё. Это приводит к тому, что извлечение не работает для некоторых корректных URL плейлистов.

**Текущий код:**
<https://github.com/kotisoff/discord-player-yandexmusic/blob/main/src/YandexMusicExtractor.ts#L23>
```typescript
private YaRegex: YaRegex = {
        playlist: /(^https:)\/\/music\.yandex\.[A-Za-z]+\/users\/[A-Za-z0-9]+\/playlists\/[0-9]+/,
        ...
}
```

**Предлагаемое решение:**
Обновить регулярное выражение, чтобы включить дополнительные допустимые символы:
```typescript
playlist: /(^https:)\/\/music\.yandex\.[A-Za-z]+\/users\/[A-Za-z0-9._=-]+\/playlists\/[0-9]+/
```

**Comment by kotisoff** [comment]
Понял, спасибо.
